### ISSUE TITLE
Add data for JSConf EU 2018

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#10]
In the [data directory](https://github.com/EddyVinck/ConfTalks/tree/master/client/data) you will find a few files with relational data.

Please add the videos from JSConf EU 2018 in the same way I already added the videos for JSConf 2019. You can find the videos here: https://www.youtube.com/playlist?list=PL37ZVnwpeshG2YXJkun_lyNTtM-Qb3MKa

Please review the [contributing guidelines for adding talks](https://github.com/EddyVinck/ConfTalks/blob/master/CONTRIBUTING.md#adding-talks).

Please let me know if you start working on this. If you have any questions, you can ask them here or in our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

If a talk has not been upload you can leave the `video_url` empty and put in a date like `1999-12-30` or something silly like that.

Keep in mind that you might need to update your IDs so they are unique after making a pull request if someone else's PR gets merged first. This means you will need to merge the master branch into your fork as described in the contribution guidelines.

If you are interested in conferences or ConfTalks and want to stay up to date you can [subscribe to our newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe).

Also, if you want to add any other conference, you can create an issue for it if you want. I'll be sure to add the hacktoberfest tag when I see them.

**Comment by deniskond** [comment]
@EddyVinck Hi, I would like to work on this :) Do I understand correctly that the task only requires updating json files with the data from youtube playlist? No additional logic is required to show new videos?

**Comment by EddyVinck** [comment]
Yes that is correct! Thanks @deniskond ! Make sure you've forked the last version of the project as I have merged a couple PRs with other data.

**Comment by EddyVinck** [comment]
@deniskond Please let me know when you start working on this and I will assign you to the issue

**Comment by deniskond** [comment]
@EddyVinck I opened PR with JS Conf 2018 data: https://github.com/EddyVinck/ConfTalks/pull/17

**Comment by EddyVinck** [comment]
merged! thanks for your contribution @deniskond! If you haven't already (and would like to) you can join our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM) and our [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe).
