### ISSUE TITLE
Turn the <select /> elements into combobox / multi-select versions with Downshift.

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#19]
For the Filters on ConfTalks we currently use a standard `<select />` element. I'd like to swap those out for a nice searchable combobox using Downshift: https://github.com/downshift-js/downshift

Please review the [contributing guidelines for adding talks](https://github.com/EddyVinck/ConfTalks/blob/master/CONTRIBUTING.md#adding-talks).

Please let me know if you start working on this. If you have any questions, you can ask them here or in our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

If you are interested in conferences or ConfTalks and want to stay up to date you can [subscribe to our newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe).

**Comment by EddyVinck** [comment]
I'm going to bed now. If you'd like to take this issue just post a comment and start contributing. I'll merge it tomorrow after work! :)

**Comment by jez321** [comment]
Hi! Would it be ok if I had a go at implementing this?

**Comment by EddyVinck** [comment]
Yes definitely @jez321! If you have any questions you can ask them here or on Slack.
