### ISSUE TITLE
Add data about CSS Conf EU 2019

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#2]
In the [data directory](https://github.com/EddyVinck/ConfTalks/tree/master/client/data) you will find a few files with relational data.

Please add the videos from CSS Conf EU 2019 in the same way I already added the videos for JSConf 2019. You can find the videos here: https://www.youtube.com/playlist?list=PL37ZVnwpeshERVKLkJdt5lpjJ1xqEJc17

Please review the [contributing guidelines for adding talks](https://github.com/EddyVinck/ConfTalks/blob/master/CONTRIBUTING.md#adding-talks).

Let me know if you start working on this. If you have any questions, you can ask them here or in our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

Also, if you want to add any other conference, you can create an issue for it if you want. I'll be sure to add the hacktoberfest tag when I see them. 

Keep in mind that you might need to update your IDs so they are unique after making a pull request if someone else's PR gets merged first. This means you will need to merge the master branch into your fork as described in the contribution guidelines.

I'm going to bed now, so I'll review any PRs in the morning!

**Comment by GabsRTX** [comment]
i want to working on this.

**Comment by GabsRTX** [comment]
I want to work on this.

**Comment by swatisingh45** [comment]
I wanna work on this, thanks!
