### ISSUE TITLE
Add data for JAMStack Conf SF 2019

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#24]
In the [data directory](https://github.com/EddyVinck/ConfTalks/tree/master/client/data) you will find a few files with relational data. Please review the [contributing guidelines for adding talks](https://github.com/EddyVinck/ConfTalks/blob/master/CONTRIBUTING.md#adding-talks) for info on the formatting.

Add the videos from the conference in the same way the data is already formatted. You can find the videos here: 
- [JAMStack Conf SF 2019](https://www.youtube.com/playlist?list=PL58Wk5g77lF_gCGGqbVZMBun9x70yC4o-)

Let me know if you start working on this. If you have any questions, you can ask them here or in our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

If a talk has not been uploaded yet you can leave the `video_url` empty and put in a date like `2021-12-30` or a data when the video will be uploaded for sure.

💌 You can [subscribe to our newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you are interested in conferences or ConfTalks and want to stay up to date.

**Also, if you want to add any other conference, you can create an issue for it if you want. I'll be sure to add the hacktoberfest tag when I see them.**

**Comment by jonhenshaw** [comment]
I would like to work on this!

**Comment by EddyVinck** [comment]
Go ahead @Jon309 ! Thanks!

**Comment by jonhenshaw** [comment]
#26 Finished!

**Comment by EddyVinck** [comment]
@Jon309 Thank you for your contribution! I'll check it out after work. Be sure to join our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM) and [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you would like to get involved :slightly_smiling_face:

**Comment by jonhenshaw** [comment]
I made an additional PR to fix an incorrect link! #37

**Comment by EddyVinck** [comment]
Thanks again @Jon309 ! Please join our [Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM) and [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you'd like to stay in touch! or open another PR, that works as well :wink:
