### ISSUE TITLE
Add data for React Amsterdam 2019

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#25]
In the [data directory](https://github.com/EddyVinck/ConfTalks/tree/master/client/data) you will find a few files with relational data. Please review the [contributing guidelines for adding talks](https://github.com/EddyVinck/ConfTalks/blob/master/CONTRIBUTING.md#adding-talks) for info on the formatting.

Add the videos from the conference in the same way the data is already formatted. You can find the videos here: 
- [React Amsterdam 2019](https://www.youtube.com/playlist?list=PLNBNS7NRGKMHLTeH4qfD3F320GXfj97kc)

Don't add videos like an aftermovie of course :slightly_smiling_face: 

Let me know if you start working on this. If you have any questions, you can ask them here or in our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

If a talk has not been uploaded yet you can leave the `video_url` empty and put in a date like `2021-12-30` or a data when the video will be uploaded for sure.

💌 You can [subscribe to our newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you are interested in conferences or ConfTalks and want to stay up to date.

**Also, if you want to add any other conference, you can create an issue for it if you want. I'll be sure to add the hacktoberfest tag when I see them.**

**Comment by reegoram** [comment]
Hello! Can I take this one?

**Comment by EddyVinck** [comment]
@reegoram yes go ahead! Thanks for contributing!

**Comment by EddyVinck** [comment]
@reegoram Thank you for your contribution. I'll check it out after work. Be sure to join our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM) and [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you would like to get involved :slightly_smiling_face:
