### ISSUE TITLE
Add data for PyCon 2018

### ISSUE THREAD

**Issue by villabunterkunt** [EddyVinck/ConfTalks#33]
[Youtube](https://www.youtube.com/channel/UCsX05-2sVSH7Nx3zuk3NYuQ/videos)

Resources:
[Contributing Guidelines](https://github.com/EddyVinck/ConfTalks/blob/master/CONTRIBUTING.md)
[Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM)

Notes:
If a talk has not been uploaded you can leave the video_url empty and put in a random date
You might need to update the IDs in case another PR is merged first

**Comment by EddyVinck** [comment]
Thanks for the conference suggestion! For anyone who is interested in working on this please note that we also have a [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) 💌

Also note that you can make issues for any conference you would like to add 😁

**Comment by meganvbarton** [comment]
I would like to work on this.

**Comment by EddyVinck** [comment]
Hi @meganvbarton, that would be great! :slightly_smiling_face: You can start now if you want, but I'm going to merge in some other PRs so you might have to end up updating your IDs again before I can merge your PR. If  you have any questions you can ask them on here or on [Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).  

We also have a [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) 💌

**Comment by meganvbarton** [comment]
@EddyVinck we can close this issue now that my PR has been merged!

**Comment by EddyVinck** [comment]
You're right @meganvbarton, thanks!
