### ISSUE TITLE
Add JamStackConf SF 2019

### ISSUE THREAD

**Issue by DAMMAK** [EddyVinck/ConfTalks#35]
here is the youtube playlist for JAMstack Conf SF 2019

https://www.youtube.com/watch?v=LnYrJ7X00XM&list=PL58Wk5g77lF_gCGGqbVZMBun9x70yC4o-

**Comment by EddyVinck** [comment]
Hi @dammak Thanks for getting involved. As you noticed this conference has already been suggested, but you're free to suggest additional conferences 😊
You can join our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM) if you want. 
**:love_letter: We also have a [newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/).**

**Comment by DAMMAK** [comment]
okay! I will do so... I love the work you are doing here.... I will contribute to it as much as possible...
