### ISSUE TITLE
Make a better logo for ConfTalks

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#36]
Right now we have a [pretty simple logo](https://github.com/EddyVinck/ConfTalks/blob/master/client/assets/logo.png) I created but I'm not very good at this sort of thing.

If you could create a logo that would be very much appreciated. Some things to keep in mind:
- Preferably use the colors used for the [ConfTalks website](https://conftalks.org), but don't use more than a few colors. Less is more.
- The logo should be easily identifiable when it is small as a favicon (the icon in your browser tab)
- Keep it simple, I'd like to have some stickers made some day and maybe some other printed stuff
- You can read more about ConfTalks in the [DEV.to announcement](https://dev.to/eddyvinck/i-created-my-first-open-source-project-in-7-days-and-released-it-today-12d5).

If you have any questions, you can ask them here or in our [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

💌 You can [subscribe to our newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you are interested in conferences or ConfTalks and want to stay up to date.

**Also, if you want to add any other development related conference, you can create an issue for it if you want. I'll be sure to add the hacktoberfest tag when I see them.**

**Comment by EddyVinck** [comment]
@vishwasmattur Thank you for your contribution! The logo looks great! :tada: 

If I can make a slight suggestion: would you be willing to make an additional version without the text? and an additional version without the text and maybe a solid background for the favicon?

If you'd rather use Slack for communication about the logo you can join us here in the [community Slack](https://join.slack.com/t/conftalks/shared_invite/enQtNzk1MjA1ODQ2NzM3LTRkMmU0YmRhZDEzYmUxZTEyYjhlMWYzOWIyYTU0NDBkMGFlN2U3MjJmNWE5MjM4ZDM1Yzg0M2QwZWUzODllMzM).

Again thanks so much for the contribution @vishwasmattur! It really is appreciated :+1: 

You can also [subscribe to our newsletter](https://emailoctopus.com/lists/b6cc50a1-f282-11e9-be00-06b4694bee2a/forms/subscribe) if you want :slightly_smiling_face:

**Comment by vishwasmattur** [comment]
Sure thing. Sorry for the late response.
