### ISSUE TITLE
Bug: some authors aren't displayed correctly

### ISSUE THREAD

**Issue by EddyVinck** [EddyVinck/ConfTalks#45]
https://github.com/EddyVinck/ConfTalks/pull/41

In Megan's PR she mentions the data is correct, but displayed incorrectly. This needs to be looked into and fixed.

**Comment by jglover** [comment]
I may have time to look at this, let me do a spike. I suspect it's the array slicing and use of numeric index keys in the JSON objects having a subtle bug.

**Comment by EddyVinck** [comment]
I'd appreciate that @jglover. Thanks!

**Comment by EddyVinck** [comment]
@jglover seems the bug was caused by some duplicate IDs, I'm closing this now
