### ISSUE TITLE
[FEATURE] Add topics to the filter

### ISSUE THREAD

**Issue by dios-david** [EddyVinck/ConfTalks#6]
I think it would be nice to have an option to filter talks based on their topics.
The implementation would be just adding a "Topic" dropdown into the Filters box on the left side.

Alternatively, it can be a multi-value input where you can select multiple topics at the same time.

**Comment by EddyVinck** [comment]
Something like this definitely needs to be added. I already planned to turn the `<select />` elements into combobox / multi-select versions with [Downshift](https://github.com/downshift-js/downshift).

**Comment by EddyVinck** [comment]
@dios-david The categories filter was just pushed to production. Going to make a separate issue for turning them into a nice combobox
